# Spotify Pulse

## Notebook 01 - Data Understanding

### Author
Aayush Gupta

### Project
Spotify Pulse – AI-powered Product Analytics Platform

### Objective

The objective of this notebook is to understand the three raw datasets used in the Spotify Pulse project before any preprocessing or modeling.

This notebook focuses on:

- Understanding dataset structure
- Identifying available features
- Assessing data quality
- Mapping datasets to business objectives
- Planning the next preprocessing steps

In [25]:
import pandas as pd 
import numpy as np

## Loading the Raw Datasets

In [26]:
import os

print(os.getcwd())

c:\Intern season\Spotify-pulse\notebooks

In [27]:
print(os.listdir())

['01_data_understanding.ipynb', 'notebooks']

In [28]:
print(os.listdir("../data/raw"))

['spotify_streaming_history.csv', 'spotify_user_behavior.csv', 'spotify_user_preferences.xlsx']

Small improvement to our workflow

From now on, whenever we get a file-related error, we'll follow this checklist:

Where am I?

os.getcwd()

What files are here?

os.listdir()

What files are in the target folder?

os.listdir("../data/raw")

This approach saves a lot of time compared to trial and error.

In [29]:
streaming_history = pd.read_csv("../data/raw/spotify_streaming_history.csv")

user_behavior = pd.read_csv("../data/raw/spotify_user_behavior.csv")

user_preferences = pd.read_excel("../data/raw/spotify_user_preferences.xlsx")

In [30]:
# Checking dimensions

print("Streaming History:", streaming_history.shape)
print("User Behavior:", user_behavior.shape)
print("User Preferences:", user_preferences.shape)

Streaming History: (149860, 11)
User Behavior: (8000, 12)
User Preferences: (520, 20)

In [31]:
# =====================================================
# Dataset Overview
# =====================================================

datasets = {
    "Streaming History": streaming_history,
    "User Behavior": user_behavior,
    "User Preferences": user_preferences
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)
    print(f"Shape: {df.shape}")
    print("\nColumns:")
    print(list(df.columns))
    print("\n")

============================================================
Streaming History
============================================================
Shape: (149860, 11)

Columns:
['spotify_track_uri', 'ts', 'platform', 'ms_played', 'track_name', 'artist_name', 'album_name', 'reason_start', 'reason_end', 'shuffle', 'skipped']


============================================================
User Behavior
============================================================
Shape: (8000, 12)

Columns:
['user_id', 'gender', 'age', 'country', 'subscription_type', 'listening_time', 'songs_played_per_day', 'skip_rate', 'device_type', 'ads_listened_per_week', 'offline_listening', 'is_churned']


============================================================
User Preferences
============================================================
Shape: (520, 20)

Columns:
['Age', 'Gender', 'spotify_usage_period', 'spotify_listening_device', 'spotify_subscription_plan', 'premium_sub_willingness', 'preffered_premium_plan', 'preferred_listening_content', 'fav_music_genre', 'music_time_slot', 'music_Influencial_mood', 'music_lis_frequency', 'music_expl_method', 'music_recc_rating', 'pod_lis_frequency', 'fav_pod_genre', 'preffered_pod_format', 'pod_host_preference', 'preffered_pod_duration', 'pod_variety_satisfaction']

In [32]:
# =====================================================
# First 5 Rows of Each Dataset
# =====================================================

datasets = {
    "Streaming History": streaming_history,
    "User Behavior": user_behavior,
    "User Preferences": user_preferences
}

for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)

    display(df.head(4))

    print("\n")

================================================================================
Streaming History
================================================================================

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False

================================================================================
User Behavior
================================================================================

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0
2,3,Male,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Female,22,CA,Student,36,2,0.31,Mobile,0,1,0

================================================================================
User Preferences
================================================================================

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating,pod_lis_frequency,fav_pod_genre,preffered_pod_format,pod_host_preference,preffered_pod_duration,pod_variety_satisfaction
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok

Streaming History -
1. One user who is listening using spotify and his activity is being tracked - Song, artist, album, platform, ms played, time, reason of start and end, shuffle, skip
"The data strongly suggests it is one user."

what each column of this dataset tells us and helps for our analysis
1. we can identify what kind of songs/mood the user likes to listed based on ms played and the frequency of the song played and the similar mood songs played - 
2. We can identify which artists he likes to listen to
3. we can identify for how much time and at which parts of the day he usually uses spotify to listen to songs - this is a v imp data point for every user
4. 

User behaviour -

In [33]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    print(df.columns.tolist())
    print("\n")

================================================================================
Streaming History
================================================================================
['spotify_track_uri', 'ts', 'platform', 'ms_played', 'track_name', 'artist_name', 'album_name', 'reason_start', 'reason_end', 'shuffle', 'skipped']


================================================================================
User Behavior
================================================================================
['user_id', 'gender', 'age', 'country', 'subscription_type', 'listening_time', 'songs_played_per_day', 'skip_rate', 'device_type', 'ads_listened_per_week', 'offline_listening', 'is_churned']


================================================================================
User Preferences
================================================================================
['Age', 'Gender', 'spotify_usage_period', 'spotify_listening_device', 'spotify_subscription_plan', 'premium_sub_willingness', 'preffered_premium_plan', 'preferred_listening_content', 'fav_music_genre', 'music_time_slot', 'music_Influencial_mood', 'music_lis_frequency', 'music_expl_method', 'music_recc_rating', 'pod_lis_frequency', 'fav_pod_genre', 'preffered_pod_format', 'pod_host_preference', 'preffered_pod_duration', 'pod_variety_satisfaction']

In [34]:
for name, df in datasets.items():
    print("=" * 80)
    print(name)
    print("=" * 80)

    display(df.dtypes.to_frame("Data Type"))

================================================================================
Streaming History
================================================================================

                  Data Type
spotify_track_uri       str
ts                      str
platform                str
ms_played             int64
track_name              str
artist_name             str
album_name              str
reason_start            str
reason_end              str
shuffle                bool
skipped                bool

================================================================================
User Behavior
================================================================================

                      Data Type
user_id                   int64
gender                      str
age                       int64
country                     str
subscription_type           str
listening_time            int64
songs_played_per_day      int64
skip_rate               float64
device_type                 str
ads_listened_per_week     int64
offline_listening         int64
is_churned                int64

================================================================================
User Preferences
================================================================================

                            Data Type
Age                               str
Gender                            str
spotify_usage_period              str
spotify_listening_device          str
spotify_subscription_plan         str
premium_sub_willingness           str
preffered_premium_plan            str
preferred_listening_content       str
fav_music_genre                   str
music_time_slot                   str
music_Influencial_mood            str
music_lis_frequency               str
music_expl_method                 str
music_recc_rating               int64
pod_lis_frequency                 str
fav_pod_genre                     str
preffered_pod_format              str
pod_host_preference               str
preffered_pod_duration            str
pod_variety_satisfaction          str